apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9091
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.44.0
      cacheLevel: High
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      exemplarTraceIdDestinations:
        - datasourceUid: my_jaeger_uid
          name: traceID
        - name: traceID
          url: http://localhost:3002/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Jaeger%22,%7B%22query%22:%22$${__value.raw}%22%7D%5D
  - name: Jaeger
    type: jaeger
    uid: EbPG8fYoz
    url: http://jaeger:1200
    access: proxy
    basicAuth: false
    readOnly: false
    isDefault: false
  - name: elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9300
    jsonData:
      index: my-log-index
      interval: Daily
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: fields.level
      dataLinks:
        - datasourceUid: my_jaeger_uid
          field: traceID
          url: $${__value.raw}
